export const GET_ALL_CENTERS = 'GET_ALL_CENTERS';
export const GET_ALL_CENTERS_FULFILLED = 'GET_ALL_CENTERS_FULFILLED';
export const GET_ALL_CENTERS_REJECTED = 'GET_ALL_CENTERS_REJECTED';

export const ADD_CENTER = 'ADD_CENTER';
export const ADD_CENTER_FULFILLED = 'ADD_CENTER_FULFILLED';
export const ADD_CENTER_REJECTED = 'ADD_CENTER_REJECTED';

export const GET_CENTER = 'GET_CENTER';
export const GET_CENTER_FULFILLED = 'GET_CENTER_FULFILLED';
export const GET_CENTER_REJECTED = 'GET_CENTER_REJECTED';

export const MODIFY_CENTER = 'MODIFY_CENTER';
export const MODIFY_CENTER_FULFILLED = 'MODIFY_CENTER_FULFILLED';
export const MODIFY_CENTER_REJECTED = 'MODIFY_CENTER_REJECTED';
