export const GET_ALL_CENTERS = 'GET_ALL_CENTERS';
export const GET_ALL_CENTERS_FULFILLED = 'GET_ALL_CENTERS_FULFILLED';
export const GET_ALL_CENTERS_REJECTED = 'GET_ALL_CENTERS_REJECTED';

export const ADD_CENTER = 'ADD_CENTER';
export const ADD_CENTER_FULFILLED = 'ADD_CENTER_FULFILLED';
export const ADD_CENTER_REJECTED = 'ADD_CENTER_REJECTED';

export const GET_CENTER = 'GET_CENTER';
export const GET_CENTER_FULFILLED = 'GET_CENTER_FULFILLED';
export const GET_CENTER_REJECTED = 'GET_CENTER_REJECTED';

export const MODIFY_CENTER = 'MODIFY_CENTER';
export const MODIFY_CENTER_FULFILLED = 'MODIFY_CENTER_FULFILLED';
export const MODIFY_CENTER_REJECTED = 'MODIFY_CENTER_REJECTED';

export const DELETE_CENTER = 'DELETE_CENTER';
export const DELETE_CENTER_FULFILLED = 'DELETE_CENTER_FULFILLED';
export const DELETE_CENTER_REJECTED = 'DELETE_CENTER_REJECTED';

export const GET_CENTER_EVENTS = 'GET_CENTER_EVENTS';
export const GET_CENTER_EVENTS_FULFILLED = 'GET_CENTER_EVENTS_FULFILLED';
export const GET_CENTER_EVENTS_REJECTED = 'GET_CENTER_EVENTS_REJECTED';

export const CANCEL_CENTER_EVENT = 'CANCEL_CENTER_EVENT';
export const CANCEL_CENTER_EVENT_FULFILLED = 'CANCEL_CENTER_EVENT_FULFILLED';
export const CANCEL_CENTER_EVENT_REJECTED = 'CANCEL_CENTER_EVENT_REJECTED';

