export const GET_ALL_CENTERS = 'GET_ALL_CENTERS';
export const GET_ALL_CENTERS_FULFILLED = 'GET_ALL_CENTERS_FULFILLED';
export const GET_ALL_CENTERS_REJECTED = 'GET_ALL_CENTERS_REJECTED';

export const ADD_CENTER = 'ADD_CENTER';
export const ADD_CENTER_FULFILLED = 'ADD_CENTER_FULFILLED';
export const ADD_CENTER_REJECTED = 'ADD_CENTER_REJECTED';