export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENT_FULFILLED = 'ADD_EVENT_FULFILLED';
export const ADD_EVENT_REJECTED = 'ADD_EVENT_REJECTED';

export const GET_EVENT = 'GET_EVENT';
export const GET_EVENT_FULFILLED = 'GET_EVENT_FULFILLED';
export const GET_EVENT_REJECTED = 'GET_EVENT_REJECTED';

export const MODIFY_EVENT = 'MODIFY_EVENT';
export const MODIFY_EVENT_FULFILLED = 'MODIFY_EVENT_FULFILLED';
export const MODIFY_EVENT_REJECTED = 'MODIFY_EVENT_REJECTED';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_FULFILLED = 'DELETE_EVENT_FULFILLED';
export const DELETE_EVENT_REJECTED = 'DELETE_EVENT_REJECTED';

export const GET_USER_EVENTS = 'GET_USER_EVENTS';
export const GET_USER_EVENTS_FULFILLED = 'GET_USER_EVENTS_FULFILLED';
export const GET_USER_EVENTS_REJECTED = 'GET_USER_EVENTS_REJECTED';

export const CANCEL_EVENT = 'CANCEL_EVENT_EVENT';
export const CANCEL_EVENT_FULFILLED = 'CANCEL_EVENT_FULFILLED';
export const CANCEL_EVENT_REJECTED = 'CANCEL_EVENT_REJECTED';
