export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENT_FULFILLED = 'ADD_EVENT_FULFILLED';
export const ADD_EVENT_REJECTED = 'ADD_EVENT_REJECTED';

export const GET_EVENT = 'GET_EVENT';
export const GET_EVENT_FULFILLED = 'GET_EVENT_FULFILLED';
export const GET_EVENT_REJECTED = 'GET_EVENT_REJECTED';

export const MODIFY_EVENT = 'MODIFY_EVENT_EVENT';
export const MODIFY_EVENT_FULFILLED = 'MODIFY_EVENT_FULFILLED';
export const MODIFY_EVENT_REJECTED = 'MODIFY_EVENT_REJECTED';